#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Usuário RLS'
        hostname: zropc
        username: rls
        password: '$y$j9T$8Uu4aXs.NK6TT3Ky0HgFw.$S1NiIhz8GBfNMWbEYV4PZrYHImEYj90PYNq2uSvmgTB'  # BBZro@2020
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    storage:
        layout:
            name: direct  # usa layout simples, sem LVM
    updates: none
    codecs:
        install: false
    drivers:
        install: false
    shutdown: reboot
