#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: zropc
    username: efsj
    password: "$6$TUXC5wz9YqXrmFqa$gQUXXMxihtSHXgoJeYUmvvJ8Cdf9bOgmD9AGmhDsyN5PIHDTvFWPVckbACBC7k6hIpEAp1hqyPz8fOaU3ivMC/"
  locale: pt_BR
  keyboard:
    layout: br
    variant: abnt2
  timezone: America/Sao_Paulo

  storage:
    config:
      - type: disk
        id: disk0
        match:
          size: largest
        wipe: superblock
        preserve: false
        name: primary
        grub_device: true
        size: 100%
        children:
          - type: partition
            id: primary-partition
            size: 100%
            format: ext4
            mount: /
      - type: luks
        id: luks1
        name: encrypted_disk
        device: /dev/sda1
        passphrase: "sito ague tons anjo seja cepa"
        format: ext4
        mount: /mnt/encrypted
        options:
          luks: true
        children:
          - type: partition
            id: encrypted-partition
            size: 100%
            format: ext4
            mount: /mnt

