#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Usuário RLS'
        hostname: zropc
        username: rls
        password: '$y$j9T$8Uu4aXs.NK6TT3Ky0HgFw.$S1NiIhz8GBfNMWbEYV4PZrYHImEYj90PYNq2uSvmgTB'  # BBZro@2020
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    storage:
        layout:
            name: lvm
        swap:
            size: 0
        encryption:
            enabled: true
            passphrase: 'caso remo doca loto ames toso'
    packages:
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
