#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: usuario
    password: "$6$gSa1WhOC3K$G.6VdwG8LsU7Sm9JPh09FvLxjcvHXDN8s82pajWkAwPQU86HQO0UkOemQoR4sq4mhVeFMXnbJFaO/MnPvXluZ0"
  locale: en_US
  keyboard:
    layout: us
  timezone: America/Sao_Paulo
  apt:
    preserve_sources_list: false
    primary:
      - arches: [amd64]
        uri: http://archive.ubuntu.com/ubuntu

  storage:
    layout:
      name: direct
    config:
      - type: disk
        id: disk0
        match:
          model: nvme0n1
        wipe: superblock-recursive
        ptable: gpt

      - type: partition
        id: efi
        device: disk0
        size: 512M
        flag: boot
        filesystem: fat32
        mount: /boot/efi

      - type: partition
        id: boot
        device: disk0
        size: 1024M
        filesystem: ext4
        mount: /boot

      - type: partition
        id: crypt
        device: disk0
        size: -1
        wipe: superblock
        preserve: false
        grub_device: false

      - type: luks
        id: luks_root
        device: crypt
        key: 
          passphrase: "sito ague tons ajo seja cepa"
        wipe: superblock
        preserve: false

      - type: lvm_volgroup
        id: vg0
        name: vg0
        devices: [luks_root]

      - type: lvm_logical_volume
        id: lv_root
        name: root
        volgroup: vg0
        size: 20G
        filesystem: ext4
        mount: /

      - type: lvm_logical_volume
        id: lv_home
        name: home
        volgroup: vg0
        size: -1
        filesystem: ext4
        mount: /home

  user-data:
    disable_root: false

  ssh:
    install-server: true
    allow-pw: true

  updates: security
  packages:
    - vim
    - curl
